name: "Request for Access to Collaboration Tools"
description: "Use this template to request access to shared tools like Google Drive, GitHub, and Notion boards."
title: "Request for Access to Collaboration Tools for [your project name]"
assignees: "oeaugustin"
labels: 
  - access-request
body:
  - type: markdown
    attributes:
      value: |
        ## Team Information
  - type: input
    id: project_name
    attributes:
      label: "Project Name"
      description: "Enter your project name here"
      placeholder: "e.g., Collaboration Dashboard Project"
  - type: textarea
    id: team_members
    attributes:
      label: "Team Members + Emails + Github Username"
      description: "Enter the names, emails,and Github (if needed) of all team members that need access"
      placeholder: "e.g., John Doe, johndoe@bu.edu, johndoe"
  - type: markdown
    attributes:
      value: |
        ## Tool Access
        Please specify which tools you need access to and describe the reason for each one.
  - type: checkboxes
    id: tools_needed
    attributes:
      label: "Select Tools Needed"
      description: "Check the tools you need access to"
      options:
        - label: "Google Drive"
        - label: "GitHub"
        - label: "Notion Board"
        - label: "Slack"
        - label: "Other (specify below)"
  - type: textarea
    id: additional_tools
    attributes:
      label: "Additional Tools (if needed)"
      description: "List any other tools you need access to and explain their usage"
      placeholder: "e.g., Miro for brainstorming, Jira for task management"
