name: Build Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-preview:
    runs-on: ubuntu-latest
    name: Build Preview Site and Upload Build Artifact
    if: ${{ github.event.pull_request.head.repo.fork == true }}
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4  # Set the Ruby version

      # Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Build the Jekyll site with the specified config file
      - name: Build site
        run: jekyll build --config _config.prod.yml
        env:
          RUBY_VERSION: 3.3.4  
          
      # Upload the build directory as a workflow artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-build
          path: _site
