name: Pull Request
on: pull_request

jobs:
  pr_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - run: bundle install && bundle exec jekyll build
  preview:
    needs: pr_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BU_SPARK_TECH_RESOURCES }}"
          projectId: bu-spark-tech-resources
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels